// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDBvZ5yRHMc0wglyLO4I-73cK_PbAWOi4',
    appId: '1:1078699012413:web:e4552b03355537bae8d554',
    messagingSenderId: '1078699012413',
    projectId: 'focusflow-8b702',
    authDomain: 'focusflow-8b702.firebaseapp.com',
    storageBucket: 'focusflow-8b702.firebasestorage.app',
    measurementId: 'G-9S8BDVM634',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN6-tiK3obcfbqXxoS7n3ewiKlvJQOb1o',
    appId: '1:1078699012413:android:33d5e7f9bbc2130be8d554',
    messagingSenderId: '1078699012413',
    projectId: 'focusflow-8b702',
    storageBucket: 'focusflow-8b702.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDBvZ5yRHMc0wglyLO4I-73cK_PbAWOi4',
    appId: '1:1078699012413:web:08dbf66df4785879e8d554',
    messagingSenderId: '1078699012413',
    projectId: 'focusflow-8b702',
    authDomain: 'focusflow-8b702.firebaseapp.com',
    storageBucket: 'focusflow-8b702.firebasestorage.app',
    measurementId: 'G-WZSTCVVBLZ',
  );
}
