class LanguageDictionary {
  static Map<String, Map<String, String>> texts = {
    'en': {
      //English
      "ok": "OK",
      "at": "at",
      "add": "Add",
      "save": "Save",
      "cancel": "Cancel",
      "delete": "Delete",
      "current": "Current",
      "work_dur": "Work Duration (min.)",
      "break_dur": "Break Duration (min.)",
      "block_dur": "Block Duration (min.)",
      "start": "Start",
      "pause": "Pause",
      "reset": "Reset",
      "work": "Work",
      "break": "Break",
      "set_difficulty": "Set Difficulty",
      "difficulty": "Difficulty",
      "dark_mode": 'Dark Mode',
      "font_size": 'Font Size',
      "settings_adjust_font_size": "Adjust Font Size",
      "long_break": "Long Break",
      "routines": "Routines",
      "add_group": "Add Group",
      "working_technique": "Working Technique",
      "edit_routine": "Edit Routine",
      'home_page_welcome': 'Welcome to Focus Flow',
      'home_page_goto_routine_screen': 'Go To Routine Screen',
      'home_page_settings': 'Settings',
      'routine_screen_my_routines': "My Routines",
      "routine_screen_working_techniques": "Working Techniques",
      "routine_screen_task_handling": "Task/Routine Handling",
      "routine_screen_home": "Home",
      "routine_screen_calendar": "Calendar",
      "routine_screen_settings": "Settings",
      "routine_screen_profile": "Profile",
      "routine_screen_create_routine_for": "Technique: ",
      "routine_list_routines": "Current Routines",
      "routine_list_delete_routine": "Delete Routine",
      "routine_list_delete_routine_confirm":
          'Are you sure you want to delete this routine?',
      "routine_c_form_routine_title": "Routine Title",
      "routine_c_form_hint_routine_title": 'Enter your routine title',
      "routine_c_form_set_reminder": "Set Reminder",
      "routine_c_form_reminder": "Reminder:",
      "routine_c_form_add_routine": "Add Routine",
      "routine_details_routine_details": "Routine Details",
      "action_button_unsuported_technique": "Unsupported Technique",
      "action_button_start_pomodoro": "Start Pomodoro Session",
      "action_button_start_time_b": "Start Time Blocking Session",
      "action_button_start_zen": "Start Zen Session",
      "action_button_isnt_supported": "is not supported yet.",
      "edit_dialog_reminder_date_and_time": "Reminder Date and Time",
      "routine_header_scheduled_for": "Scheduled for",
      "calendar_routine_calendar": 'Routine Calendar',
      "calendar_no_routines_for_the_day": 'No tasks for this day.',
      "task_batching_add_custom_group": "Add Custom Group",
      "task_batching_hint_group_name": "Enter group name",
      "task_batching_add_to_custom_group": "Add to Custom Group",
      "task_batching_no_custom_group_available": "No custom groups available.",
      "time_block_complete": "Time Block Complete!",
      "time_block_complete_message":
          "You've successfully completed this time block.",
      "pomodoro_complete": "Pomodoro Complete!",
      "pomodoro_complete_message":
          "You've successfully completed this pomodoro.",
      "post_it_hint_text": 'Write something...',
      "post_it_saved": "Notes Saved",
      "eisenhower_important_urgent": 'Important & Urgent',
      "eisenhower_important_not_urgent": 'Important & Not Urgent',
      "eisenhower_not_important_urgent": 'Not Important & Urgent',
      "eisenhower_not_important_not_urgent": 'Not Important & Not Urgent',
      "eisenhower_technical_groups": "Technical Groups",
      "eisenhower_matrix": "Eisenhower Matrix",
      "eisenhower_move_to_quadrant": "Move to Quadrant",
      "time_blocking_delete_routine_confirm":
          'You completed this time block. Do you want to delete this routine?',
      "pomodoro_delete_routine_confirm":
          'You completed this pomodoro. Do you want to delete this routine?',
      "select_language": "Select Language",
      "eat_that_frog_enter_difficulty": "Enter difficulty",
      "technique_groups": "Technique Groups",
      "custom_groups": "Custom Groups",
      "delete_group": "Delete Group",
    },
    'tr': {
      //Türkçe
      "ok": "Tamam",
      "at": "Saat",
      "add": "Ekle",
      "save": "Kaydet",
      "cancel": "İptal",
      "delete": "Sil",
      "current": "Mevcut",
      "work_dur": "Çalışma Süresi (dak.)",
      "break_dur": "Mola Süresi (dak.)",
      "block_dur": "Blok Süresi (dak.)",
      "start": "Başla",
      "pause": "Durdur",
      "reset": "Sıfırla",
      "work": "Çalış",
      "break": "Mola",
      "set_difficulty": "Zorluk Belirle",
      "difficulty": "Zorluk",
      "dark_mode": 'Karanlık Mod',
      "font_size": 'Font Boyutu',
      "settings_adjust_font_size": "Font Boyutunu Ayarla",
      "long_break": "Uzun Mola",
      "routines": "Rutinler",
      "add_group": "Grup Ekle",
      "working_technique": "Çalışma Tekniği",
      "edit_routine": "Rutini Düzenle",
      'home_page_welcome': 'Focus Flow\'a Hoşgeldiniz',
      'home_page_goto_routine_screen': 'Rutin Ekranına Git',
      'home_page_settings': 'Ayarlar',
      'routine_screen_my_routines': "Rutinlerim",
      "routine_screen_working_techniques": "Çalışma Teknikleri",
      "routine_screen_task_handling": "Görev / Rutin Yönetimi",
      "routine_screen_home": "Ana Sayfa",
      "routine_screen_calendar": "Takvim",
      "routine_screen_settings": "Ayarlar",
      "routine_screen_profile": "Profil",
      "routine_screen_create_routine_for": "Teknik: ",
      "routine_list_routines": "Mevcut Rutinler",
      "routine_list_delete_routine": "Rutini Sil",
      "routine_list_delete_routine_confirm":
          'Bu rutini silmek istediğinizden emin misiniz?',
      "routine_c_form_routine_title": "Rutin Başlığı",
      "routine_c_form_hint_routine_title": "Rutin başlığınızı yazın",
      "routine_c_form_set_reminder": "Hatırlatıcı Ekle",
      "routine_c_form_reminder": "Hatırlatıcı:",
      "routine_c_form_add_routine": "Rutin Ekle",
      "routine_details_routine_details": "Rutin Detayları",
      "action_button_unsuported_technique": "Desteklenmeyen Teknik",
      "action_button_start_pomodoro": "Pomodoro Oturumuna Başla",
      "action_button_start_time_b": "Zaman Bloklama Oturumuna Başla",
      "action_button_start_zen": "Sükunet Oturumuna Başla",
      "action_button_isnt_supported": "henüz desteklenmiyor.",
      "edit_dialog_reminder_date_and_time": "Hatırlatıcı Tarihi ve Zamanı",
      "routine_header_scheduled_for": "Planladı: ",
      "calendar_routine_calendar": 'Rutin Takvimi',
      "calendar_no_routines_for_the_day": 'Bugün için rutin yok.',
      "task_batching_add_custom_group": "Özel Grup Ekle",
      "task_batching_hint_group_name": "Grup adını girin",
      "task_batching_add_to_custom_group": "Özel Gruba Ekle",
      "task_batching_no_custom_group_available": "Uygun özel grup bulunumadı.",
      "time_block_complete": "Zaman Bloklama Tamamlandı!",
      "time_block_complete_message": "Bu zaman bloğunu başarıyla tamamladın.",
      "pomodoro_complete": "Pomodoro Tamamlandı!",
      "pomodoro_complete_message": "Bu Pomodoroyu başarıyla tamamladın.",
      "post_it_hint_text": 'Bir şeyler yaz...',
      "post_it_saved": "Notlar Kaydedildi",
      "eisenhower_important_urgent": 'Önemli ve Acil',
      "eisenhower_important_not_urgent": 'Önemli ve Acil Değil',
      "eisenhower_not_important_urgent": 'Önemsiz ve Acil',
      "eisenhower_not_important_not_urgent": 'Önemsiz ve Acil Değil',
      "eisenhower_technical_groups": "Teknik Grupları",
      "eisenhower_matrix": "Eisenhower Matrisi",
      "eisenhower_move_to_quadrant": "Matrise Ata",
      "time_blocking_delete_routine_confirm":
          'Bu Zaman Bloğunu Tamamladın. Bu rutini silmek ister misin?',
      "pomodoro_delete_routine_confirm":
          'Bu Pomodoroyu bitirdin. Bu rutini silmek ister misin?',
      "select_language": "Dil Seçin",
      "eat_that_frog_enter_difficulty": "Zorluğu girin",
      "technique_groups": "Teknik Gruplar",
      "custom_groups": "Özel Gruplar",
      "delete_group": "Grubu Sil",
    },
    'fr': {
      // French
      "ok": "D'accord",
      "at": "à",
      "add": "Ajouter",
      "save": "Sauvegarder",
      "cancel": "Annuler",
      "delete": "Supprimer",
      "current": "Actuel",
      "work_dur": "Durée de Travail (min.)",
      "break_dur": "Durée de Pause (min.)",
      "block_dur": "Durée du Bloc (min.)",
      "start": "Démarrer",
      "pause": "Pause",
      "reset": "Réinitialiser",
      "work": "Travail",
      "break": "Pause",
      "set_difficulty": "Définir la Difficulté",
      "difficulty": "Difficulté",
      "dark_mode": 'Mode Sombre',
      "font_size": 'Taille de Police',
      "settings_adjust_font_size": "Ajuster la Taille de Police",
      "long_break": "Longue Pause",
      "routines": "Routines",
      "add_group": "Ajouter un Groupe",
      "working_technique": "Technique de Travail",
      "edit_routine": "Modifier la Routine",
      "home_page_welcome": 'Bienvenue dans Focus Flow',
      "home_page_goto_routine_screen": 'Aller à l’Écran des Routines',
      "home_page_settings": 'Paramètres',
      "routine_screen_my_routines": "Mes Routines",
      "routine_screen_working_techniques": "Techniques de Travail",
      "routine_screen_task_handling": "Gestion des Tâches / Routines",
      "routine_screen_home": "Accueil",
      "routine_screen_calendar": "Calendrier",
      "routine_screen_settings": "Paramètres",
      "routine_screen_profile": "Profil",
      "routine_screen_create_routine_for": "Technique : ",
      "routine_list_routines": "Routines Actuelles",
      "routine_list_delete_routine": "Supprimer la Routine",
      "routine_list_delete_routine_confirm":
          'Êtes-vous sûr de vouloir supprimer cette routine ?',
      "routine_c_form_routine_title": "Titre de la Routine",
      "routine_c_form_hint_routine_title": "Entrez le titre de votre routine",
      "routine_c_form_set_reminder": "Définir un Rappel",
      "routine_c_form_reminder": "Rappel :",
      "routine_c_form_add_routine": "Ajouter une Routine",
      "routine_details_routine_details": "Détails de la Routine",
      "action_button_unsuported_technique": "Technique Non Supportée",
      "action_button_start_pomodoro": "Démarrer une Session Pomodoro",
      "action_button_start_time_b": "Démarrer une Session de Bloc de Temps",
      "action_button_start_zen": "Démarrer une Session Zen",
      "action_button_isnt_supported": "n'est pas encore supportée.",
      "edit_dialog_reminder_date_and_time": "Date et Heure du Rappel",
      "routine_header_scheduled_for": "Prévu pour",
      "calendar_routine_calendar": 'Calendrier des Routines',
      "calendar_no_routines_for_the_day": 'Pas de tâches pour ce jour.',
      "task_batching_add_custom_group": "Ajouter un Groupe Personnalisé",
      "task_batching_hint_group_name": "Entrez le nom du groupe",
      "task_batching_add_to_custom_group": "Ajouter au Groupe Personnalisé",
      "task_batching_no_custom_group_available":
          "Aucun groupe personnalisé disponible.",
      "time_block_complete": "Bloc de Temps Terminé !",
      "time_block_complete_message":
          "Vous avez réussi à terminer ce bloc de temps.",
      "pomodoro_complete": "Pomodoro Terminé !",
      "pomodoro_complete_message": "Vous avez réussi à terminer ce pomodoro.",
      "post_it_hint_text": 'Écrivez quelque chose...',
      "post_it_saved": "Notes Enregistrées",
      "eisenhower_important_urgent": 'Important & Urgent',
      "eisenhower_important_not_urgent": 'Important & Non Urgent',
      "eisenhower_not_important_urgent": 'Pas Important & Urgent',
      "eisenhower_not_important_not_urgent": 'Pas Important & Non Urgent',
      "eisenhower_technical_groups": "Groupes Techniques",
      "eisenhower_matrix": "Matrice Eisenhower",
      "eisenhower_move_to_quadrant": "Déplacer vers le Quadrant",
      "time_blocking_delete_routine_confirm":
          'Vous avez terminé ce bloc de temps. Voulez-vous supprimer cette routine ?',
      "pomodoro_delete_routine_confirm":
          'Vous avez terminé ce pomodoro. Voulez-vous supprimer cette routine ?',
      "select_language": "Choisissez la Langue",
      "eat_that_frog_enter_difficulty": "Entrer la difficulté",
      "technique_groups": "Les Groupes Techniques",
      "custom_groups": "Groupes Personnalisés",
      "delete_group": "Supprimer un groupe",
    },
    'de': {
      // German
      "ok": "OK",
      "at": "um",
      "add": "Hinzufügen",
      "save": "Speichern",
      "cancel": "Abbrechen",
      "delete": "Löschen",
      "current": "Aktuell",
      "work_dur": "Arbeitsdauer (Min.)",
      "break_dur": "Pausendauer (Min.)",
      "block_dur": "Blockdauer (Min.)",
      "start": "Starten",
      "pause": "Pause",
      "reset": "Zurücksetzen",
      "work": "Arbeit",
      "break": "Pause",
      "set_difficulty": "Schwierigkeit Festlegen",
      "difficulty": "Schwierigkeit",
      "dark_mode": 'Dunkelmodus',
      "font_size": 'Schriftgröße',
      "settings_adjust_font_size": "Schriftgröße Anpassen",
      "long_break": "Lange Pause",
      "routines": "Routinen",
      "add_group": "Gruppe Hinzufügen",
      "working_technique": "Arbeitstechnik",
      "edit_routine": "Routine Bearbeiten",
      "home_page_welcome": 'Willkommen bei Focus Flow',
      "home_page_goto_routine_screen": 'Zur Routinen-Seite Gehen',
      "home_page_settings": 'Einstellungen',
      "routine_screen_my_routines": "Meine Routinen",
      "routine_screen_working_techniques": "Arbeitstechniken",
      "routine_screen_task_handling": "Aufgaben- / Routinenverwaltung",
      "routine_screen_home": "Startseite",
      "routine_screen_calendar": "Kalender",
      "routine_screen_settings": "Einstellungen",
      "routine_screen_profile": "Profil",
      "routine_screen_create_routine_for": "Technik: ",
      "routine_list_routines": "Aktuelle Routinen",
      "routine_list_delete_routine": "Routine Löschen",
      "routine_list_delete_routine_confirm":
          'Sind Sie sicher, dass Sie diese Routine löschen möchten?',
      "routine_c_form_routine_title": "Routinetitel",
      "routine_c_form_hint_routine_title": "Geben Sie den Routinetitel ein",
      "routine_c_form_set_reminder": "Erinnerung Festlegen",
      "routine_c_form_reminder": "Erinnerung:",
      "routine_c_form_add_routine": "Routine Hinzufügen",
      "routine_details_routine_details": "Routinedetails",
      "action_button_unsuported_technique": "Nicht Unterstützte Technik",
      "action_button_start_pomodoro": "Pomodoro-Session Starten",
      "action_button_start_time_b": "Zeitblock-Session Starten",
      "action_button_start_zen": "Zen-Session Starten",
      "action_button_isnt_supported": "wird noch nicht unterstützt.",
      "edit_dialog_reminder_date_and_time": "Erinnerungsdatum und -zeit",
      "routine_header_scheduled_for": "Geplant für",
      "calendar_routine_calendar": 'Routinenkalender',
      "calendar_no_routines_for_the_day": 'Keine Aufgaben für diesen Tag.',
      "task_batching_add_custom_group": "Benutzerdefinierte Gruppe Hinzufügen",
      "task_batching_hint_group_name": "Gruppenname Eingeben",
      "task_batching_add_to_custom_group":
          "Zur Benutzerdefinierten Gruppe Hinzufügen",
      "task_batching_no_custom_group_available":
          "Keine Benutzerdefinierten Gruppen Verfügbar.",
      "time_block_complete": "Zeitblock Abgeschlossen!",
      "time_block_complete_message":
          "Sie haben diesen Zeitblock erfolgreich abgeschlossen.",
      "pomodoro_complete": "Pomodoro Abgeschlossen!",
      "pomodoro_complete_message":
          "Sie haben dieses Pomodoro erfolgreich abgeschlossen.",
      "post_it_hint_text": 'Schreiben Sie etwas...',
      "post_it_saved": "Notizen Gespeichert",
      "eisenhower_important_urgent": 'Wichtig & Dringend',
      "eisenhower_important_not_urgent": 'Wichtig & Nicht Dringend',
      "eisenhower_not_important_urgent": 'Unwichtig & Dringend',
      "eisenhower_not_important_not_urgent": 'Unwichtig & Nicht Dringend',
      "eisenhower_technical_groups": "Technische Gruppen",
      "eisenhower_matrix": "Eisenhower-Matrix",
      "eisenhower_move_to_quadrant": "In Quadrant Verschieben",
      "time_blocking_delete_routine_confirm":
          'Sie haben diesen Zeitblock abgeschlossen. Möchten Sie diese Routine löschen?',
      "pomodoro_delete_routine_confirm":
          'Sie haben dieses Pomodoro abgeschlossen. Möchten Sie diese Routine löschen?',
      "select_language": "Sprache Auswählen",
      "eat_that_frog_enter_difficulty": "Schwierigkeiten eingeben",
      "technique_groups": "Technische Gruppen",
      "custom_groups": "Benutzerdefinierte Gruppen",
      "delete_group": "Gruppe löschen"
    },
    'es': {
      // Spanish
      "ok": "Aceptar",
      "at": "a las",
      "add": "Añadir",
      "save": "Guardar",
      "cancel": "Cancelar",
      "delete": "Eliminar",
      "current": "Actual",
      "work_dur": "Duración del Trabajo (min.)",
      "break_dur": "Duración del Descanso (min.)",
      "block_dur": "Duración del Bloque (min.)",
      "start": "Iniciar",
      "pause": "Pausar",
      "reset": "Reiniciar",
      "work": "Trabajar",
      "break": "Descanso",
      "set_difficulty": "Establecer Dificultad",
      "difficulty": "Dificultad",
      "dark_mode": 'Modo Oscuro',
      "font_size": 'Tamaño de Fuente',
      "settings_adjust_font_size": "Ajustar Tamaño de Fuente",
      "long_break": "Descanso Largo",
      "routines": "Rutinas",
      "add_group": "Añadir Grupo",
      "working_technique": "Técnica de Trabajo",
      "edit_routine": "Editar Rutina",
      "home_page_welcome": 'Bienvenido a Focus Flow',
      "home_page_goto_routine_screen": 'Ir a la Pantalla de Rutinas',
      "home_page_settings": 'Configuración',
      "routine_screen_my_routines": "Mis Rutinas",
      "routine_screen_working_techniques": "Técnicas de Trabajo",
      "routine_screen_task_handling": "Gestión de Tareas / Rutinas",
      "routine_screen_home": "Inicio",
      "routine_screen_calendar": "Calendario",
      "routine_screen_settings": "Configuración",
      "routine_screen_profile": "Perfil",
      "routine_screen_create_routine_for": "Técnica: ",
      "routine_list_routines": "Rutinas Actuales",
      "routine_list_delete_routine": "Eliminar Rutina",
      "routine_list_delete_routine_confirm":
          '¿Estás seguro de que deseas eliminar esta rutina?',
      "routine_c_form_routine_title": "Título de Rutina",
      "routine_c_form_hint_routine_title": "Introduce el título de la rutina",
      "routine_c_form_set_reminder": "Establecer Recordatorio",
      "routine_c_form_reminder": "Recordatorio:",
      "routine_c_form_add_routine": "Añadir Rutina",
      "routine_details_routine_details": "Detalles de la Rutina",
      "action_button_unsuported_technique": "Técnica No Soportada",
      "action_button_start_pomodoro": "Iniciar Sesión Pomodoro",
      "action_button_start_time_b": "Iniciar Sesión de Bloque de Tiempo",
      "action_button_start_zen": "Iniciar Sesión Zen",
      "action_button_isnt_supported": "aún no es soportado.",
      "edit_dialog_reminder_date_and_time": "Fecha y Hora del Recordatorio",
      "routine_header_scheduled_for": "Programado para",
      "calendar_routine_calendar": 'Calendario de Rutinas',
      "calendar_no_routines_for_the_day": 'No hay tareas para este día.',
      "task_batching_add_custom_group": "Añadir Grupo Personalizado",
      "task_batching_hint_group_name": "Introduce el nombre del grupo",
      "task_batching_add_to_custom_group": "Añadir al Grupo Personalizado",
      "task_batching_no_custom_group_available":
          "No hay grupos personalizados disponibles.",
      "time_block_complete": "¡Bloque de Tiempo Completado!",
      "time_block_complete_message":
          "Has completado con éxito este bloque de tiempo.",
      "pomodoro_complete": "¡Pomodoro Completado!",
      "pomodoro_complete_message": "Has completado con éxito este pomodoro.",
      "post_it_hint_text": 'Escribe algo...',
      "post_it_saved": "Notas Guardadas",
      "eisenhower_important_urgent": 'Importante y Urgente',
      "eisenhower_important_not_urgent": 'Importante y No Urgente',
      "eisenhower_not_important_urgent": 'No Importante y Urgente',
      "eisenhower_not_important_not_urgent": 'No Importante y No Urgente',
      "eisenhower_technical_groups": "Grupos Técnicos",
      "eisenhower_matrix": "Matriz de Eisenhower",
      "eisenhower_move_to_quadrant": "Mover al Cuadrante",
      "time_blocking_delete_routine_confirm":
          'Has completado este bloque de tiempo. ¿Quieres eliminar esta rutina?',
      "pomodoro_delete_routine_confirm":
          'Has completado este pomodoro. ¿Quieres eliminar esta rutina?',
      "select_language": "Seleccionar Idioma",
      "eat_that_frog_enter_difficulty": "ntroducir dificultad",
      "technique_groups": "Grupos Técnicos",
      "custom_groups": "Grupos personalizados",
      "delete_group": "Borrar grupo",
    },
  };
}
